version: '2'
services: 
    elasticsearch:
        build: ./elasticsearch
        container_name: elasticsearch
        ports: 
            - 9200:9200
        volumes:
            - /Volumes/elasticsearch/:/usr/share/elasticsearch/data
    kibana:
        build: ./kibana
        container_name: kibana
        environment:
            ELASTICSEARCH_URL: http://elasticsearch:9200
        ports:
            - 5601:5601
    logstash:
        build: ./logstash
        container_name: logstash
        volumes: 
            - /Volumes/logstash:/usr/share/logstash/pipeline/